# Generated by Django 5.0.2 on 2024-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero_commande',
            field=models.IntegerField(default=0),
        ),
    ]
